default:

release_ios:
	security unlock-keychain
	mono ~/src/fuselibs/Stuff/uno.exe build --target=iOS --configuration=Release DupesyChristmas.unoproj

release_android:
	mono ~/src/fuselibs/Stuff/uno.exe build --target=Android --configuration=Release DupesyChristmas.unoproj